### ISSUE TITLE
Question about code of spark.py

### ISSUE THREAD

**Issue by ctrajan** [ChenghaoMou/text-dedup#12]
thanks for the great code, I have some understanding problems about the following code:
```
a = edges
    while True:
        b = a.flatMap(large_star_map).groupByKey().flatMap(large_star_reduce).distinct().cache()
        a = b.map(small_star_map).groupByKey().flatMap(small_star_reduce).distinct().cache()
        changes = a.subtract(b).union(b.subtract(a)).collect()
        if len(changes) == 0:
            break
```
this code is used to clustering the total docs by the generated edges(which means duplication) and remove the duplicated docs? If so, variable ``` a ``` is the texts after dedup?

**Comment by ChenghaoMou** [comment]
This particular piece is indeed clustering edges into connected components. This is described in paper https://dl.acm.org/doi/10.1145/2670979.2670997.

To give an example, the input (edges) before the while loop:

| x | y | 
|--------|--------|
|2 | 1|
|2 | 3|

The output after the while loop is something like this:

| id | component | 
|--------|--------|
|2 | 1|
|3 | 1|

But the duplicates are not removed here, they are removed at line https://github.com/ChenghaoMou/text-dedup/blob/14ea1ed5e8b8b1cb190f1261e82629ace1d668fc/text_dedup/spark.py#L270

Any node that does have a component id assigned, in this case 2 and 3 will be removed. 1 is kept, along with any node that is not included in the edges in the first place.

**Comment by KeremTurgutlu** [comment]
If interested, there is a [presentation](https://www.youtube.com/watch?v=Io1x6mQlh1E) from one of the authors.

**Comment by ctrajan** [comment]
@ChenghaoMou @KeremTurgutlu thanks for your presentations, that's helpful
