### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by KeremTurgutlu** [ChenghaoMou/text-dedup#13]
I've noticed that the [latest release](https://github.com/ChenghaoMou/text-dedup/releases/tag/0.2.1) doesn't have the suffix array changes made in [this commit](https://github.com/ChenghaoMou/text-dedup/commit/9325445667a7bae0a7de38f6af3d35c226d14d45). Do you plan to make a new pip release?

Thanks once again for the great work!

**Comment by ChenghaoMou** [comment]
Thanks for asking, it is intentional. I am transitioning from a PyPI package to a pure script-based repo to encourage people to read and update the code for their needs. Previous PyPI packages had some very different design decisions, I will retire them when the time is right.

**Comment by KeremTurgutlu** [comment]
That makes sense, thanks for providing concise scripts for each pipeline :)
