### ISSUE TITLE
Suffix array clean up

### ISSUE THREAD

**Issue by KeremTurgutlu** [ChenghaoMou/text-dedup#14]
I think [here](https://github.com/ChenghaoMou/text-dedup/blob/14ea1ed5e8b8b1cb190f1261e82629ace1d668fc/text_dedup/suffix_array.py#L268-L271) instead of removing slices from the string array we should remove from the byte array since suffix array deduplication code returns byte pair pointers. Since a utf-8 character can be represented by 1-4 bytes this can lead to errors with text that have at least 1 character with > 1 bytes.

Maybe something like this

```python
def clean_up(text, remove_pairs):
    """
    Remove duplicate substrings from the text.
    Parameters
    """
    byte_array = np.array(list(text.encode()))
    for start, end in remove_pairs:
        byte_array[start:end] = -1 # byte must be between 0-256
    return bytearray([byte for byte in byte_array if byte != -1]).decode("utf-8", "ignore") 
```

Let me know if I am missing something regarding `suffix_array.py` code which might already handle this.

**Comment by ChenghaoMou** [comment]
Good catch. Thanks for pointing it out, I have fixed it in the the latest commit.

**Comment by KeremTurgutlu** [comment]
No worries, this is the least I can do to contribute back. Also, here is a minor addition if you like:

Motivation is that there might be cases where k length duplicate text start at one document and finishes in another. In order to avoid that I believe original repo includes a [unique separator](https://github.com/google-research/deduplicate-text-datasets/blob/ad86c7f65ac626581fe3a4277106309bc6b50c23/scripts/load_dataset.py#L87).

A similar thing can be done in this repo: 

```
        with timer("Preprocessing"):
            offsets: List[slice] = []
            start = 0
            with open(Path(args.google_repo_path) / temp_text, "wb") as f:
                for UID, doc in enumerate(ds):
                    SEP = b"\xff\xff" + struct.pack("<I", UID)
                    doc_bytes = SEP + doc[args.column].encode("utf-8")
                    end = start + len(doc_bytes)
                    offsets.append(slice(start, end))
                    start = end
                    f.write(doc_bytes)
```

```
def clean_up(text, slices, UID):
    """
    Remove duplicate substrings from the text.
    Parameters
    """
    SEP_LENGTH = len(b"\xff\xff" + struct.pack("<I", UID))
    byte_array = np.array(list(text.encode()))
    for s in slices:
        byte_array[s.start-SEP_LENGTH:s.stop-SEP_LENGTH] = -1 # byte must be between 0-256
    return bytearray([byte for byte in byte_array if byte != -1]).decode("utf-8", "ignore")
```

**Comment by ChenghaoMou** [comment]
If I read this correctly, this is not needed in my implementation, actually. It keeps track of the document byte level boundaries (offsets) in the beginning [code](https://github.com/ChenghaoMou/text-dedup/blob/91cb8b011393d144439f67a5540d6a97a49cf266/text_dedup/suffix_array.py#L308), before merging everything into one giant string, and will [restore](https://github.com/ChenghaoMou/text-dedup/blob/91cb8b011393d144439f67a5540d6a97a49cf266/text_dedup/suffix_array.py#L116) them when generating those slices, so each generated slice respects the document boundary without any special token.
