### ISSUE TITLE
Issue with NON_ALPHA Regular Expression for Multilingual Support

### ISSUE THREAD

**Issue by Hank0626** [ChenghaoMou/text-dedup#24]
The current `NON_ALPHA = re.compile("[^A-Za-z]")` is not adequate for multilingual support. For example, `NON_ALPHA.split("你好")` returns `['', '', '']` instead of the expected `['你好']`. I recommend using `re.compile("\W", re.UNICODE)` to accommodate all languages properly.

**Comment by ChenghaoMou** [comment]
This is a great point! I have left a small comment in the PR. I am happy to merge them once it is updated.
