### ISSUE TITLE
refactor hash related code

### ISSUE THREAD

**Issue by chris-ha458** [ChenghaoMou/text-dedup#29]
This code base utilizes several different kinds of hashes (md5, SHA-1, xxhash, sha256).
Some are implemented in redundant manners.
For instance, `sha1_hash32` in minhash_spark and `sha1_hash` (with default d=32) in minhash.py
seem to achieve the same thing.
I think that refactoring it like the [hashfunc.py](https://github.com/ekzhu/datasketch/blob/master/datasketch/hashfunc.py) in `ekzhu/datasketch` could be helpful.

if I prepared a PR, would you consider it?

**Comment by ChenghaoMou** [comment]
Thanks for the PR. It is duplicated (somehow ironic considering the name) because it allows us to submit a Pyspark job without declaring additional Python files or dependencies. That also reminds me of another issue — rn the spark script imports the `ngram` function from the other file, and I need to change that.

But it is probably a good choice for other type of algorithms. So I will approve the PR.

Thanks again for your help!

**Comment by chris-ha458** [comment]
If I understand you correctly, atleast for PySpark based `minhash_spark.py`, we cannot include any dependencies outside python standard library or pyspark functions right? (since each executor will also need to have it installed and coordinating that is possible but difficult).
Seems like there are some pyspark functions in this case.
[xxhash64](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.xxhash64.html#pyspark.sql.functions.xxhash64)

Otherwise, I will continue another PR that
imports and uses the new consolidated hash functions and remove redundant ones, except for `minhash_spark.py`

For `minhash_spark.py`, I will
1. implement `blake2b_hash` without any dependency except hashlib and struct
2. investigate how to utilize [xxhash64](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.xxhash64.html#pyspark.sql.functions.xxhash64) for this purpose.

**Comment by chris-ha458** [comment]
Most of my suggestions were implemented through #30 #35 #48
Some more are ongoing. There are more to be implemented but I think this issue can be closed
