### ISSUE TITLE
ModuleNotFoundError: No module named 'text_dedup.embedders'

### ISSUE THREAD

**Issue by done520** [ChenghaoMou/text-dedup#4]
ModuleNotFoundError: No module named 'text_dedup.embedders'

when "from text_dedup.embedders.minhash import MinHashEmbedder"

**Comment by ChenghaoMou** [comment]
Can I ask what version of `text_dedup` you are using?

If it is installed from PyPi, then this shouldn't be an issue. But if you are using the `main` branch, then there are some breaking changes that the documentation hasn't caught up with, in which case, you can write:

```
from text_dedup.near_dedup import MinHashEmbedder
```

The documentation should be updated in the next couple of days.

**Comment by done520** [comment]
thanks. I would like to ask if text_dedup can be used for academic paper duplicate testing?  Have you ever tried that?

**Comment by ChenghaoMou** [comment]
By `for academic paper duplicate testing`, can you clarify what do you mean exactly?
1. Deduplicating data when the data are academic papers
2. Using this in for a research paper for testing other datasets

**Comment by done520** [comment]
@ChenghaoMou such as duplicate checking of graduation thesis to determine whether the article is plagiarized.

**Comment by paperClub-hub** [comment]
I'm sorry to reply now and many thanks for your fruitful suggestions and proposals.
