### ISSUE TITLE
Error when running on Windows10

### ISSUE THREAD

**Issue by soonjune** [ChenghaoMou/text-dedup#50]
In `minhash.py` line 223
```
mp.set_start_method("fork", force=True)
```
should be
```
mp.set_start_method("spawn", force=True)
``` 
in Windows OS.

https://github.com/woven-planet/l5kit/issues/129

**Comment by chris-ha458** [comment]
I think the answer is more involved than that.

Spawn is more expensive but fork is unavailable in windows.

Also there are sane safe defaults for each platform.

I think the answer should be what the original issue you refer to takes.

If sys.platform == Darwin
 mp.set_startmethod
Like this.

I'll try to prepare a pr that also adds comments

**Comment by chris-ha458** [comment]
@soonjune can you try and see if this works for you?
https://github.com/ChenghaoMou/text-dedup/pull/51

**Comment by ChenghaoMou** [comment]
Fork behaviour is required for the copy-on-write mechanism to work on the `uf` object. This was discussed in https://github.com/ChenghaoMou/text-dedup/issues/26#issuecomment-1636787593. Until someone has access to a Windows machine and thoroughly tests the memory impact, allowing spawn might lead to more problems than it solves.

**Comment by chris-ha458** [comment]
Considering that it isnt JUST a MacOS thing, I resorted to documenting it in a PR with various housekeeping changes.

**Comment by ChenghaoMou** [comment]
I am closing it for now. Feel free to reopen if you have any other issues.
