### ISSUE TITLE
Raising errors on subprocess calls rather than logging

### ISSUE THREAD

**Issue by TevenLeScao** [ChenghaoMou/text-dedup#6]
What it says on the tin, I strongly feel that the `logger.error` at https://github.com/ChenghaoMou/text-dedup/blob/main/text_dedup/exact_dedup/suffix_array/suffix_array_google.py#L135 should be a `RuntimeError` instead so that it doesn't go on with broken things + the bug stands out to you and/or the debugger.

**Comment by ChenghaoMou** [comment]
Thank you for reporting the issue! It has been updated in the main branch.

**Comment by TevenLeScao** [comment]
Thanks! Lemme know if I should just open a PR next time for tweaks like this
