### ISSUE TITLE
Deduplication of union find clusters explained

### ISSUE THREAD

**Issue by ZJaume** [ChenghaoMou/text-dedup#62]
Hi, I've been reading your code of MinHash deduplication to find differences with my implementations or ideas of optimization. Is the filtering step using UnionFind parents to keep non duplicates and one sample of each cluster? That is why understand from here
https://github.com/ChenghaoMou/text-dedup/blob/e7b8401a297212c9764c1b0c8f6d89ba6a601dce/text_dedup/minhash.py#L300

At least, that is what I've been doing in my code, filter every sample id that union find vector says it is not a parent.

Also, may I ask why sharding is needed? Is the HF dataset class able to unload from memory and only allocate the current shard?
https://github.com/ChenghaoMou/text-dedup/blob/e7b8401a297212c9764c1b0c8f6d89ba6a601dce/text_dedup/minhash.py#L262-L272

**Comment by ChenghaoMou** [comment]
1. Yes;
2. Sharding is introduced as an alternative to batching; this is more for the dataset iteration itself than actual deduplication. Iteration, one by one, is slow with large datasets.

**Comment by ZJaume** [comment]
Alright, many thanks.
