### ISSUE TITLE
Papers, Datasets that use this repo

### ISSUE THREAD

**Issue by chris-ha458** [ChenghaoMou/text-dedup#65]
Recently the paper for [CulturaX](https://arxiv.org/abs/2309.09400) a dataset utilizing text-dedup has been released.

I am sure there are many more including the stack.

Would it be valuable to have some mentions regarding these kind of use cases in the `README.md`? 
I'll prepare a PR if there is interest.

**Comment by scheiblr** [comment]
@ChenghaoMou, maybe [zenodo](https://zenodo.org/) would be an option to you, so that researcher can cite you in their work using a DOI.

**Comment by ChenghaoMou** [comment]
Citations and https://github.com/ChenghaoMou/awesome-data-deduplication have been created. Thanks for all the comments.
