### ISSUE TITLE
Can we accelerate the groupByKey operation by md5 hashing for the Minhash spark version?

### ISSUE THREAD

**Issue by 311dada** [ChenghaoMou/text-dedup#76]
Thanks for your great efforts for this excellent work first!

Recently, we have adopted this tool in our research. In detail, we used the minhash algorithm in the Spark version. Unfortunately, we found the groupByKey operation in lines [80](https://github.com/ChenghaoMou/text-dedup/blob/main/text_dedup/minhash_spark.py#L80) and [103](https://github.com/ChenghaoMou/text-dedup/blob/main/text_dedup/minhash_spark.py#L103C47-L103C57) is time-consuming. After diving into your code, we have an idea of replacing the [key](https://github.com/ChenghaoMou/text-dedup/blob/main/text_dedup/minhash_spark.py#L259) in tuple format into md5 hashing string. For example, we replace the following code (line 259 of minhash_spark.py)

`return [(band_idx, H, idx) for band_idx, H in enumerate(Hs)]`

into

`return [((calculate_md5('{}, {}'.format(band_idx, H)), idx) for band_idx, H in enumerate(Hs)]`

We empirically found such md5 string replacement can accelerate a lot. However, we cannot make sure whether this behavior has no damage to the deduplication workflow. Thus, we raise an issue here to verify it. Could you help us? Thanks a lot.

**Comment by ChenghaoMou** [comment]
Thanks, this is a great question.

Based on my limited understanding of spark and a few Google searches, the `GroupByKey` function already uses some hash-based methods such as `ObjectHashAggregate`. If you are using [md5](https://crypto.stackexchange.com/questions/1434/are-there-two-known-strings-which-have-the-same-md5-hash-value), it might lead to unnecessary collisions, theoretically, which might be okay for your use-case or data scale. 

Have you tried with just the string or some HEX string of the data?
