### ISSUE TITLE
no module named numpy._typing

### ISSUE THREAD

**Issue by Leoooooo123** [ChenghaoMou/text-dedup#83]
when i run the minhash_spark.py with spark submit, the program exit with this bug. I search the keywork in whole project and do not find any related code and also do not find any similar situation on the internet. do you know what causes the bug? thx!
![20240328-100906](https://github.com/ChenghaoMou/text-dedup/assets/40174318/f057ee8d-05f2-49ab-853a-02b0c7eb2a3b)
and my numpy version is 1.22.3

**Comment by ChenghaoMou** [comment]
Can you try upgrading numpy version to `>=1.26.4`? 

with 1.22.3:
```
>>> from numpy._typing import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy._typing'
>>> 
```

with 1.26.4
```
>>> from numpy._typing import *
>>> 
```
