### ISSUE TITLE
Failed to install using `pip install text-dedup`, but succeeded using `pip install -e .`

### ISSUE THREAD

**Issue by hancheolcho** [ChenghaoMou/text-dedup#84]
Hi, 
First, thank you for a great library :-)

When I installed text-dedup using pip install, it failed while trying to uninstall scipy library version 1.12.0 and install scipy==1.9.1.
Strange errors poped up mentioning `meson` and  `compile` ....

While digging the cause of error, I found that the repo's main branch is updated AFTER the text-dedup 0.3.1 released.
So I cloned it and installed using `pip install -e .` without any issues.

I think that text-dedup in pypi should be updated :-)

Best regards,
Han-Cheol

**Comment by ChenghaoMou** [comment]
Thanks for reminding me. It has been updated.

I will close this issue for now. Feel free to open another one if you encounter any issues.
