### ISSUE TITLE
数据读取失败

### ISSUE THREAD

**Issue by programmerLY** [ChenghaoMou/text-dedup#86]
![image](https://github.com/ChenghaoMou/text-dedup/assets/31037013/616761bd-18ed-4028-ac9b-a2bec2297841)

**Comment by ChenghaoMou** [comment]
能否提供一下你使用的命令行参数？

**Comment by programmerLY** [comment]
python -m text_dedup.minhash \
   --path "oscar-corpus/OSCAR-2201" \
   --name "ar" \
   --split "train" \
   --cache_dir "./cache" \
   --output "output/minhash/oscar_gl_dedup" \
   --column "content" \
   --batch_size 10000

**Comment by programmerLY** [comment]
感觉像是数据源有问题，因为我同样的命令行，读codeparrot/codeparrot-clean-valid 是没问题的

**Comment by ChenghaoMou** [comment]
谢谢。这样看来的话，应该缺少参数导致的HF的验证问题。OSCAR数据需要在网页上手动确认使用须知的, 然后需要加 `--use_auth_token true` 才能正常下载。

文档稍后会更新，谢谢理解。
